### ISSUE TITLE
Performance Comparison between Tape and Caliper

### ISSUE THREAD

**Issue by dexhunter** [Hyperledger-TWGC/tape#182] opened 2021-07-08 07:50 UTC
**My Config**

Fabric version: v2.2 (I am using `22393b` this commit as in [caliper v0.4.2 tutorial](https://hyperledger.github.io/caliper/v0.4.2/fabric-tutorial/tutorials-fabric-existing/))
Caliper Version: v0.4.2
Tape Version: v0.1.2
CPU: i5-7300HQ
Memory: 16 GB

![image](https://user-images.githubusercontent.com/6930518/124883230-b1f3ca00-e003-11eb-86d9-d3c723096b7a.png)

Note: I also read [Christoper's post](https://www.ibm.com/blogs/blockchain/2019/01/answering-your-questions-on-hyperledger-fabric-performance-and-scale/) on performance and scale, I think my settings are similar to the first one on the post (2 peers, 1 orderer, 4vCPU with SSDs) but I am not able to reach the similar tps neither.

**Describe the bug**
![image](https://user-images.githubusercontent.com/6930518/124881584-19a91580-e002-11eb-9d57-99930538801a.png)
![image](https://user-images.githubusercontent.com/6930518/124881675-35acb700-e002-11eb-8c1f-eba7583a4d0f.png)

I read a lot of comments that tape reaches higher TPS than caliper under the same config, but I am not able to achieve the same, so I am wondering if it was caused by my config or some internal issues. The results didn't change even I increased the `num_of_conn` & `client_per_conn` to 20 as suggested by the maintainer @SamYuan1990 

The only difference between the two frameworks is that caliper using `ReadAsset` chaincode function while tape using `GetAllAssets` chaincode function, but from my understanding, there should be no difference as both are query functions.

**Comment by dexhunter** [comment] 2021-07-08 11:49
I uploaded the log file there for reference.
[caliper.log](https://github.com/Hyperledger-TWGC/tape/files/6784170/caliper.log)

**Comment by SamYuan1990** [comment] 2021-07-08 13:27
Finally I decided to close this ticket.
As I don't want to officially say some tool is better than others or not.

**Closed by SamYuan1990** 2021-07-08 13:27 UTC
Labels: bug

**Comment by dexhunter** [comment] 2021-07-08 13:42
changed the order of execution (tape first caliper next)
![image](https://user-images.githubusercontent.com/6930518/124931819-2561ff80-e035-11eb-8901-351b1166b452.png)
![image](https://user-images.githubusercontent.com/6930518/124932123-635f2380-e035-11eb-96e3-bd73d5f32281.png)

**Comment by SamYuan1990** [comment] 2021-07-08 14:02
```
yuanyi@192 Probe % ./tape -c config.yaml -n 5000
Time     0.44s  Block   1026    Tx     10        
Time     0.80s  Block   1027    Tx     10        
Time     1.10s  Block   1028    Tx     10        
Time     1.46s  Block   1029    Tx     10        
Time     2.01s  Block   1030    Tx     10        
Time     2.39s  Block   1031    Tx     10        
Time     2.67s  Block   1032    Tx     10        
Time     3.05s  Block   1033    Tx     10        
Time     3.41s  Block   1034    Tx     10        
Time     3.75s  Block   1035    Tx     10        
Time     4.05s  Block   1036    Tx     10        
Time     4.36s  Block   1037    Tx     10        
Time     4.45s  Block   1038    Tx     10        
Time     4.48s  Block   1039    Tx     10        
Time     4.51s  Block   1040    Tx     10        
Time     4.55s  Block   1041    Tx     10        
Time     4.57s  Block   1042    Tx     10        
Time     4.61s  Block   1043    Tx     10        
Time     4.66s  Block   1044    Tx     10        
Time     4.68s  Block   1045    Tx     10        
Time     4.71s  Block   1046    Tx     10        
Time     4.75s  Block   1047    Tx     10        
Time     4.77s  Block   1048    Tx     10        
Time     4.78s  Block   1049    Tx     10        
Time     4.80s  Block   1050    Tx     10        
Time     4.82s  Block   1051    Tx     10        
Time     4.84s  Block   1052    Tx     10        
Time     4.87s  Block   1053    Tx     10        
Time     4.88s  Block   1054    Tx     10        
Time     4.90s  Block   1055    Tx     10        
Time     4.92s  Block   1056    Tx     10        
Time     4.95s  Block   1057    Tx     10        
Time     4.98s  Block   1058    Tx     10        
Time     5.00s  Block   1059    Tx     10        
Time     5.02s  Block   1060    Tx     10        
Time     5.04s  Block   1061    Tx     10        
Time     5.05s  Block   1062    Tx     10        
Time     5.07s  Block   1063    Tx     10        
Time     5.08s  Block   1064    Tx     10        
Time     5.10s  Block   1065    Tx     10        
Time     5.12s  Block   1066    Tx     10        
Time     5.14s  Block   1067    Tx     10        
Time     5.16s  Block   1068    Tx     10        
Time     5.17s  Block   1069    Tx     10        
Time     5.19s  Block   1070    Tx     10        
Time     5.22s  Block   1071    Tx     10        
Time     5.24s  Block   1072    Tx     10        
Time     5.26s  Block   1073    Tx     10        
Time     5.27s  Block   1074    Tx     10        
Time     5.30s  Block   1075    Tx     10        
Time     5.32s  Block   1076    Tx     10        
Time     5.35s  Block   1077    Tx     10        
Time     5.37s  Block   1078    Tx     10        
Time     5.40s  Block   1079    Tx     10        
Time     5.41s  Block   1080    Tx     10        
Time     5.43s  Block   1081    Tx     10        
Time     5.45s  Block   1082    Tx     10        
Time     5.47s  Block   1083    Tx     10        
Time     5.49s  Block   1084    Tx     10        
Time     5.51s  Block   1085    Tx     10        
Time     5.53s  Block   1086    Tx     10        
Time     5.55s  Block   1087    Tx     10        
Time     5.57s  Block   1088    Tx     10        
Time     5.59s  Block   1089    Tx     10        
Time     5.62s  Block   1090    Tx     10        
Time     5.64s  Block   1091    Tx     10        
Time     5.67s  Block   1092    Tx     10        
Time     5.70s  Block   1093    Tx     10        
Time     5.71s  Block   1094    Tx     10        
Time     5.73s  Block   1095    Tx     10        
Time     5.75s  Block   1096    Tx     10        
Time     5.77s  Block   1097    Tx     10        
Time     5.79s  Block   1098    Tx     10        
Time     5.80s  Block   1099    Tx     10        
Time     5.83s  Block   1100    Tx     10        
Time     5.84s  Block   1101    Tx     10        
Time     5.86s  Block   1102    Tx     10        
Time     5.88s  Block   1103    Tx     10        
Time     5.89s  Block   1104    Tx     10        
Time     5.92s  Block   1105    Tx     10        
Time     5.93s  Block   1106    Tx     10        
Time     5.95s  Block   1107    Tx     10        
Time     5.97s  Block   1108    Tx     10        
Time     5.99s  Block   1109    Tx     10        
Time     6.01s  Block   1110    Tx     10        
Time     6.03s  Block   1111    Tx     10        
Time     6.05s  Block   1112    Tx     10        
Time     6.07s  Block   1113    Tx     10        
Time     6.09s  Block   1114    Tx     10        
Time     6.11s  Block   1115    Tx     10        
Time     6.13s  Block   1116    Tx     10        
Time     6.15s  Block   1117    Tx     10        
Time     6.16s  Block   1118    Tx     10        
Time     6.17s  Block   1119    Tx     10        
Time     6.18s  Block   1120    Tx     10        
Time     6.19s  Block   1121    Tx     10        
Time     6.20s  Block   1122    Tx     10        
Time     6.21s  Block   1123    Tx     10        
Time     6.22s  Block   1124    Tx     10        
Time     6.23s  Block   1125    Tx     10        
Time     6.24s  Block   1126    Tx     10        
Time     6.25s  Block   1127    Tx     10        
Time     6.26s  Block   1128    Tx     10        
Time     6.27s  Block   1129    Tx     10        
Time     6.28s  Block   1130    Tx     10        
Time     6.29s  Block   1131    Tx     10        
Time     6.30s  Block   1132    Tx     10        
Time     6.31s  Block   1133    Tx     10        
Time     6.32s  Block   1134    Tx     10        
Time     6.33s  Block   1135    Tx     10        
Time     6.34s  Block   1136    Tx     10        
Time     6.35s  Block   1137    Tx     10        
Time     6.36s  Block   1138    Tx     10        
Time     6.37s  Block   1139    Tx     10        
Time     6.38s  Block   1140    Tx     10        
Time     6.39s  Block   1141    Tx     10        
Time     6.40s  Block   1142    Tx     10        
Time     6.41s  Block   1143    Tx     10        
Time     6.42s  Block   1144    Tx     10        
Time     6.44s  Block   1145    Tx     10        
Time     6.46s  Block   1146    Tx     10        
Time     6.47s  Block   1147    Tx     10        
Time     6.48s  Block   1148    Tx     10        
Time     6.49s  Block   1149    Tx     10        
Time     6.50s  Block   1150    Tx     10        
Time     6.50s  Block   1151    Tx     10        
Time     6.51s  Block   1152    Tx     10        
Time     6.52s  Block   1153    Tx     10        
Time     6.53s  Block   1154    Tx     10        
Time     6.54s  Block   1155    Tx     10        
Time     6.56s  Block   1156    Tx     10        
Time     6.57s  Block   1157    Tx     10        
Time     6.59s  Block   1158    Tx     10        
Time     6.61s  Block   1159    Tx     10        
Time     6.62s  Block   1160    Tx     10        
Time     6.64s  Block   1161    Tx     10        
Time     6.65s  Block   1162    Tx     10        
Time     6.66s  Block   1163    Tx     10        
Time     6.68s  Block   1164    Tx     10        
Time     6.69s  Block   1165    Tx     10        
Time     6.70s  Block   1166    Tx     10        
Time     6.72s  Block   1167    Tx     10        
Time     6.73s  Block   1168    Tx     10        
Time     6.74s  Block   1169    Tx     10        
Time     6.75s  Block   1170    Tx     10        
Time     6.76s  Block   1171    Tx     10        
Time     6.78s  Block   1172    Tx     10        
Time     6.79s  Block   1173    Tx     10        
Time     6.80s  Block   1174    Tx     10        
Time     6.81s  Block   1175    Tx     10        
Time     6.82s  Block   1176    Tx     10        
Time     6.84s  Block   1177    Tx     10        
Time     6.85s  Block   1178    Tx     10        
Time     6.86s  Block   1179    Tx     10        
Time     6.88s  Block   1180    Tx     10        
Time     6.89s  Block   1181    Tx     10        
Time     6.90s  Block   1182    Tx     10        
Time     6.92s  Block   1183    Tx     10        
Time     6.93s  Block   1184    Tx     10        
Time     6.94s  Block   1185    Tx     10        
Time     6.95s  Block   1186    Tx     10        
Time     6.96s  Block   1187    Tx     10        
Time     6.98s  Block   1188    Tx     10        
Time     7.00s  Block   1189    Tx     10        
Time     7.01s  Block   1190    Tx     10        
Time     7.03s  Block   1191    Tx     10        
Time     7.04s  Block   1192    Tx     10        
Time     7.05s  Block   1193    Tx     10        
Time     7.07s  Block   1194    Tx     10        
Time     7.08s  Block   1195    Tx     10        
Time     7.09s  Block   1196    Tx     10        
Time     7.10s  Block   1197    Tx     10        
Time     7.11s  Block   1198    Tx     10        
Time     7.12s  Block   1199    Tx     10        
Time     7.14s  Block   1200    Tx     10        
Time     7.14s  Block   1201    Tx     10        
Time     7.16s  Block   1202    Tx     10        
Time     7.18s  Block   1203    Tx     10        
Time     7.19s  Block   1204    Tx     10        
Time     7.20s  Block   1205    Tx     10        
Time     7.21s  Block   1206    Tx     10        
Time     7.22s  Block   1207    Tx     10        
Time     7.23s  Block   1208    Tx     10        
Time     7.24s  Block   1209    Tx     10        
Time     7.25s  Block   1210    Tx     10        
Time     7.26s  Block   1211    Tx     10        
Time     7.27s  Block   1212    Tx     10        
Time     7.28s  Block   1213    Tx     10        
Time     7.29s  Block   1214    Tx     10        
Time     7.30s  Block   1215    Tx     10        
Time     7.31s  Block   1216    Tx     10        
Time     7.32s  Block   1217    Tx     10        
Time     7.33s  Block   1218    Tx     10        
Time     7.35s  Block   1219    Tx     10        
Time     7.36s  Block   1220    Tx     10        
Time     7.37s  Block   1221    Tx     10        
Time     7.38s  Block   1222    Tx     10        
Time     7.40s  Block   1223    Tx     10        
Time     7.41s  Block   1224    Tx     10        
Time     7.42s  Block   1225    Tx     10        
Time     7.43s  Block   1226    Tx     10        
Time     7.44s  Block   1227    Tx     10        
Time     7.45s  Block   1228    Tx     10        
Time     7.46s  Block   1229    Tx     10        
Time     7.47s  Block   1230    Tx     10        
Time     7.48s  Block   1231    Tx     10        
Time     7.49s  Block   1232    Tx     10        
Time     7.50s  Block   1233    Tx     10        
Time     7.52s  Block   1234    Tx     10        
Time     7.53s  Block   1235    Tx     10        
Time     7.54s  Block   1236    Tx     10        
Time     7.55s  Block   1237    Tx     10        
Time     7.56s  Block   1238    Tx     10        
Time     7.57s  Block   1239    Tx     10        
Time     7.59s  Block   1240    Tx     10        
Time     7.60s  Block   1241    Tx     10        
Time     7.61s  Block   1242    Tx     10        
Time     7.62s  Block   1243    Tx     10        
Time     7.64s  Block   1244    Tx     10        
Time     7.66s  Block   1245    Tx     10        
Time     7.67s  Block   1246    Tx     10        
Time     7.68s  Block   1247    Tx     10        
Time     7.69s  Block   1248    Tx     10        
Time     7.70s  Block   1249    Tx     10        
Time     7.71s  Block   1250    Tx     10        
Time     7.72s  Block   1251    Tx     10        
Time     7.74s  Block   1252    Tx     10        
Time     7.75s  Block   1253    Tx     10        
Time     7.76s  Block   1254    Tx     10        
Time     7.77s  Block   1255    Tx     10        
Time     7.78s  Block   1256    Tx     10        
Time     7.79s  Block   1257    Tx     10        
Time     7.80s  Block   1258    Tx     10        
Time     7.82s  Block   1259    Tx     10        
Time     7.83s  Block   1260    Tx     10        
Time     7.84s  Block   1261    Tx     10        
Time     7.85s  Block   1262    Tx     10        
Time     7.87s  Block   1263    Tx     10        
Time     7.88s  Block   1264    Tx     10        
Time     7.90s  Block   1265    Tx     10        
Time     7.91s  Block   1266    Tx     10        
Time     7.92s  Block   1267    Tx     10        
Time     7.93s  Block   1268    Tx     10        
Time     7.94s  Block   1269    Tx     10        
Time     7.95s  Block   1270    Tx     10        
Time     7.96s  Block   1271    Tx     10        
Time     7.97s  Block   1272    Tx     10        
Time     7.98s  Block   1273    Tx     10        
Time     7.99s  Block   1274    Tx     10        
Time     8.00s  Block   1275    Tx     10        
Time     8.02s  Block   1276    Tx     10        
Time     8.03s  Block   1277    Tx     10        
Time     8.03s  Block   1278    Tx     10        
Time     8.04s  Block   1279    Tx     10        
Time     8.05s  Block   1280    Tx     10        
Time     8.07s  Block   1281    Tx     10        
Time     8.07s  Block   1282    Tx     10        
Time     8.09s  Block   1283    Tx     10        
Time     8.10s  Block   1284    Tx     10        
Time     8.11s  Block   1285    Tx     10        
Time     8.13s  Block   1286    Tx     10        
Time     8.14s  Block   1287    Tx     10        
Time     8.15s  Block   1288    Tx     10        
Time     8.16s  Block   1289    Tx     10        
Time     8.18s  Block   1290    Tx     10        
Time     8.19s  Block   1291    Tx     10        
Time     8.19s  Block   1292    Tx     10        
Time     8.20s  Block   1293    Tx     10        
Time     8.21s  Block   1294    Tx     10        
Time     8.22s  Block   1295    Tx     10        
Time     8.24s  Block   1296    Tx     10        
Time     8.25s  Block   1297    Tx     10        
Time     8.26s  Block   1298    Tx     10        
Time     8.27s  Block   1299    Tx     10        
Time     8.28s  Block   1300    Tx     10        
Time     8.29s  Block   1301    Tx     10        
Time     8.30s  Block   1302    Tx     10        
Time     8.31s  Block   1303    Tx     10        
Time     8.32s  Block   1304    Tx     10        
Time     8.33s  Block   1305    Tx     10        
Time     8.34s  Block   1306    Tx     10        
Time     8.35s  Block   1307    Tx     10        
Time     8.36s  Block   1308    Tx     10        
Time     8.37s  Block   1309    Tx     10        
Time     8.38s  Block   1310    Tx     10        
Time     8.39s  Block   1311    Tx     10        
Time     8.40s  Block   1312    Tx     10        
Time     8.41s  Block   1313    Tx     10        
Time     8.42s  Block   1314    Tx     10        
Time     8.43s  Block   1315    Tx     10        
Time     8.44s  Block   1316    Tx     10        
Time     8.46s  Block   1317    Tx     10        
Time     8.47s  Block   1318    Tx     10        
Time     8.48s  Block   1319    Tx     10        
Time     8.49s  Block   1320    Tx     10        
Time     8.50s  Block   1321    Tx     10        
Time     8.51s  Block   1322    Tx     10        
Time     8.52s  Block   1323    Tx     10        
Time     8.53s  Block   1324    Tx     10        
Time     8.54s  Block   1325    Tx     10        
Time     8.55s  Block   1326    Tx     10        
Time     8.56s  Block   1327    Tx     10        
Time     8.57s  Block   1328    Tx     10        
Time     8.58s  Block   1329    Tx     10        
Time     8.59s  Block   1330    Tx     10        
Time     8.61s  Block   1331    Tx     10        
Time     8.62s  Block   1332    Tx     10        
Time     8.63s  Block   1333    Tx     10        
Time     8.65s  Block   1334    Tx     10        
Time     8.66s  Block   1335    Tx     10        
Time     8.67s  Block   1336    Tx     10        
Time     8.68s  Block   1337    Tx     10        
Time     8.69s  Block   1338    Tx     10        
Time     8.70s  Block   1339    Tx     10        
Time     8.71s  Block   1340    Tx     10        
Time     8.72s  Block   1341    Tx     10        
Time     8.73s  Block   1342    Tx     10        
Time     8.74s  Block   1343    Tx     10        
Time     8.75s  Block   1344    Tx     10        
Time     8.76s  Block   1345    Tx     10        
Time     8.77s  Block   1346    Tx     10        
Time     8.78s  Block   1347    Tx     10        
Time     8.79s  Block   1348    Tx     10        
Time     8.80s  Block   1349    Tx     10        
Time     8.82s  Block   1350    Tx     10        
Time     8.83s  Block   1351    Tx     10        
Time     8.84s  Block   1352    Tx     10        
Time     8.86s  Block   1353    Tx     10        
Time     8.86s  Block   1354    Tx     10        
Time     8.87s  Block   1355    Tx     10        
Time     8.88s  Block   1356    Tx     10        
Time     8.89s  Block   1357    Tx     10        
Time     8.90s  Block   1358    Tx     10        
Time     8.91s  Block   1359    Tx     10        
Time     8.92s  Block   1360    Tx     10        
Time     8.93s  Block   1361    Tx     10        
Time     8.94s  Block   1362    Tx     10        
Time     8.95s  Block   1363    Tx     10        
Time     8.96s  Block   1364    Tx     10        
Time     8.97s  Block   1365    Tx     10        
Time     8.98s  Block   1366    Tx     10        
Time     8.99s  Block   1367    Tx     10        
Time     9.00s  Block   1368    Tx     10        
Time     9.02s  Block   1369    Tx     10        
Time     9.03s  Block   1370    Tx     10        
Time     9.04s  Block   1371    Tx     10        
Time     9.05s  Block   1372    Tx     10        
Time     9.06s  Block   1373    Tx     10        
Time     9.07s  Block   1374    Tx     10        
Time     9.08s  Block   1375    Tx     10        
Time     9.09s  Block   1376    Tx     10        
Time     9.10s  Block   1377    Tx     10        
Time     9.11s  Block   1378    Tx     10        
Time     9.12s  Block   1379    Tx     10        
Time     9.12s  Block   1380    Tx     10        
Time     9.13s  Block   1381    Tx     10        
Time     9.14s  Block   1382    Tx     10        
Time     9.15s  Block   1383    Tx     10        
Time     9.16s  Block   1384    Tx     10        
Time     9.17s  Block   1385    Tx     10        
Time     9.18s  Block   1386    Tx     10        
Time     9.20s  Block   1387    Tx     10        
Time     9.21s  Block   1388    Tx     10        
Time     9.22s  Block   1389    Tx     10        
Time     9.23s  Block   1390    Tx     10        
Time     9.24s  Block   1391    Tx     10        
Time     9.25s  Block   1392    Tx     10        
Time     9.26s  Block   1393    Tx     10        
Time     9.27s  Block   1394    Tx     10        
Time     9.28s  Block   1395    Tx     10        
Time     9.29s  Block   1396    Tx     10        
Time     9.30s  Block   1397    Tx     10        
Time     9.31s  Block   1398    Tx     10        
Time     9.32s  Block   1399    Tx     10        
Time     9.33s  Block   1400    Tx     10        
Time     9.34s  Block   1401    Tx     10        
Time     9.35s  Block   1402    Tx     10        
Time     9.36s  Block   1403    Tx     10        
Time     9.37s  Block   1404    Tx     10        
Time     9.38s  Block   1405    Tx     10        
Time     9.39s  Block   1406    Tx     10        
Time     9.40s  Block   1407    Tx     10        
Time     9.41s  Block   1408    Tx     10        
Time     9.42s  Block   1409    Tx     10        
Time     9.43s  Block   1410    Tx     10        
Time     9.44s  Block   1411    Tx     10        
Time     9.46s  Block   1412    Tx     10        
Time     9.47s  Block   1413    Tx     10        
Time     9.48s  Block   1414    Tx     10        
Time     9.49s  Block   1415    Tx     10        
Time     9.50s  Block   1416    Tx     10        
Time     9.51s  Block   1417    Tx     10        
Time     9.52s  Block   1418    Tx     10        
Time     9.53s  Block   1419    Tx     10        
Time     9.54s  Block   1420    Tx     10        
Time     9.55s  Block   1421    Tx     10        
Time     9.56s  Block   1422    Tx     10        
Time     9.57s  Block   1423    Tx     10        
Time     9.58s  Block   1424    Tx     10        
Time     9.60s  Block   1425    Tx     10        
Time     9.61s  Block   1426    Tx     10        
Time     9.62s  Block   1427    Tx     10        
Time     9.63s  Block   1428    Tx     10        
Time     9.64s  Block   1429    Tx     10        
Time     9.65s  Block   1430    Tx     10        
Time     9.66s  Block   1431    Tx     10        
Time     9.67s  Block   1432    Tx     10        
Time     9.68s  Block   1433    Tx     10        
Time     9.69s  Block   1434    Tx     10        
Time     9.70s  Block   1435    Tx     10        
Time     9.71s  Block   1436    Tx     10        
Time     9.72s  Block   1437    Tx     10        
Time     9.73s  Block   1438    Tx     10        
Time     9.74s  Block   1439    Tx     10        
Time     9.75s  Block   1440    Tx     10        
Time     9.76s  Block   1441    Tx     10        
Time     9.77s  Block   1442    Tx     10        
Time     9.78s  Block   1443    Tx     10        
Time     9.79s  Block   1444    Tx     10        
Time     9.80s  Block   1445    Tx     10        
Time     9.81s  Block   1446    Tx     10        
Time     9.82s  Block   1447    Tx     10        
Time     9.83s  Block   1448    Tx     10        
Time     9.84s  Block   1449    Tx     10        
Time     9.85s  Block   1450    Tx     10        
Time     9.86s  Block   1451    Tx     10        
Time     9.87s  Block   1452    Tx     10        
Time     9.88s  Block   1453    Tx     10        
Time     9.89s  Block   1454    Tx     10        
Time     9.90s  Block   1455    Tx     10        
Time     9.91s  Block   1456    Tx     10        
Time     9.92s  Block   1457    Tx     10        
Time     9.93s  Block   1458    Tx     10        
Time     9.94s  Block   1459    Tx     10        
Time     9.95s  Block   1460    Tx     10        
Time     9.96s  Block   1461    Tx     10        
Time     9.97s  Block   1462    Tx     10        
Time     9.98s  Block   1463    Tx     10        
Time     9.99s  Block   1464    Tx     10        
Time    10.01s  Block   1465    Tx     10        
Time    10.01s  Block   1466    Tx     10        
Time    10.02s  Block   1467    Tx     10        
Time    10.03s  Block   1468    Tx     10        
Time    10.04s  Block   1469    Tx     10        
Time    10.05s  Block   1470    Tx     10        
Time    10.06s  Block   1471    Tx     10        
Time    10.07s  Block   1472    Tx     10        
Time    10.07s  Block   1473    Tx     10        
Time    10.08s  Block   1474    Tx     10        
Time    10.09s  Block   1475    Tx     10        
Time    10.10s  Block   1476    Tx     10        
Time    10.11s  Block   1477    Tx     10        
Time    10.12s  Block   1478    Tx     10        
Time    10.13s  Block   1479    Tx     10        
Time    10.14s  Block   1480    Tx     10        
Time    10.15s  Block   1481    Tx     10        
Time    10.16s  Block   1482    Tx     10        
Time    10.17s  Block   1483    Tx     10        
Time    10.18s  Block   1484    Tx     10        
Time    10.19s  Block   1485    Tx     10        
Time    10.20s  Block   1486    Tx     10        
Time    10.21s  Block   1487    Tx     10        
Time    10.21s  Block   1488    Tx     10        
Time    10.22s  Block   1489    Tx     10        
Time    10.23s  Block   1490    Tx     10        
Time    10.24s  Block   1491    Tx     10        
Time    10.25s  Block   1492    Tx     10        
Time    10.25s  Block   1493    Tx     10        
Time    10.26s  Block   1494    Tx     10        
Time    10.27s  Block   1495    Tx     10        
Time    10.28s  Block   1496    Tx     10        
Time    10.29s  Block   1497    Tx     10        
Time    10.30s  Block   1498    Tx     10        
Time    10.31s  Block   1499    Tx     10        
Time    10.31s  Block   1500    Tx     10        
Time    10.32s  Block   1501    Tx     10        
Time    10.33s  Block   1502    Tx     10        
Time    10.34s  Block   1503    Tx     10        
Time    10.35s  Block   1504    Tx     10        
Time    10.36s  Block   1505    Tx     10        
Time    10.37s  Block   1506    Tx     10        
Time    10.37s  Block   1507    Tx     10        
Time    10.38s  Block   1508    Tx     10        
Time    10.39s  Block   1509    Tx     10        
Time    10.40s  Block   1510    Tx     10        
Time    10.41s  Block   1511    Tx     10        
Time    10.41s  Block   1512    Tx     10        
Time    10.42s  Block   1513    Tx     10        
Time    10.43s  Block   1514    Tx     10        
Time    10.44s  Block   1515    Tx     10        
Time    10.44s  Block   1516    Tx     10        
Time    10.45s  Block   1517    Tx     10        
Time    10.46s  Block   1518    Tx     10        
Time    10.47s  Block   1519    Tx     10        
Time    10.48s  Block   1520    Tx     10        
Time    10.49s  Block   1521    Tx     10        
Time    10.49s  Block   1522    Tx     10        
Time    10.50s  Block   1523    Tx     10        
Time    10.51s  Block   1524    Tx     10        
Time    10.52s  Block   1525    Tx     10        
tx: 5000, duration: 10.517015595s, tps: 475.420042
```

```
2021.07.08-21:58:52.309 info  [caliper] [report-builder]        ### Test result ###
2021.07.08-21:58:52.314 info  [caliper] [report-builder] 
+-----------+-------+------+-----------------+-----------------+-----------------+-----------------+------------------+
| Name      | Succ  | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
|-----------|-------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| readAsset | 11656 | 0    | 393.8           | 0.03            | 0.00            | 0.01            | 393.8            |
+-----------+-------+------+-----------------+-----------------+-----------------+-----------------+------------------+

2021.07.08-21:58:52.315 info  [caliper] [round-orchestrator]    Finished round 1 (readAsset) in 30.106 seconds
2021.07.08-21:58:52.315 info  [caliper] [monitor.js]    Stopping all monitors
2021.07.08-21:58:52.315 info  [caliper] [report-builder]        ### All test results ###
2021.07.08-21:58:52.316 info  [caliper] [report-builder] 
+-----------+-------+------+-----------------+-----------------+-----------------+-----------------+------------------+
| Name      | Succ  | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
|-----------|-------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| readAsset | 11656 | 0    | 393.8           | 0.03            | 0.00            | 0.01            | 393.8            |
+-----------+-------+------+-----------------+-----------------+-----------------+-----------------+------------------+

2021.07.08-21:58:52.325 info  [caliper] [report-builder]        Generated report with path /Users/yuanyi/OpenSource/probe/Probe/caliper-workspace/report.html
2021.07.08-21:58:52.325 info  [caliper] [monitor.js]    Stopping all monitors
2021.07.08-21:58:52.325 info  [caliper] [worker-orchestrator]   Sending exit message to connected workers
2021.07.08-21:58:52.325 info  [caliper] [round-orchestrator]    Benchmark finished in 57.02 seconds. Total rounds: 1. Successful rounds: 1. Failed rounds: 0.
2021.07.08-21:58:52.326 info  [caliper] [caliper-engine]        Skipping end command due to benchmark flow conditioning
2021.07.08-21:58:52.326 info  [caliper] [cli-launch-manager]    Benchmark successfully finished
2021.07.08-21:58:52.326 info  [caliper] [worker-message-handler]        Worker#1 is exiting
2021.07.08-21:58:52.326 info  [caliper] [worker-message-handler]        Worker#0 is exiting
```

base on my laptop, @dexhunter, welcome for any kind of further investigate and hope you can find root cause.
